#!/bin/bash

# Deploy blue version
kubectl apply -f blue_deployment.yaml

# Deploy green version
kubectl apply -f green_deployment.yaml

# Apply service
kubectl apply -f kubeservice.yaml

echo "Deployments and service applied."

# Get green pod name
GREEN_POD=$(kubectl get pods -l app=django,version=green -o jsonpath="{.items[0].metadata.name}")

# Check logs for errors
echo "Checking logs for green deployment..."
kubectl logs $GREEN_POD
